server {
 
    listen 80;
 
    server_name ITAMS;  # Change this to your domain or IP in production
    # root /var/www/product-ticket;  # Ensure this matches the Docker volume path
    root "/var/www/html/public";
 
    index index.php index.html index.htm;
    # Specify the maximum allowed size of the client request body
    client_max_body_size 100M;
    # Handle requests for static files directly, pass all others to index.php
 
    location / {
 
        try_files $uri $uri/ /index.php?$query_string;
 
    }
    # Handle CORS pre-flight requests
 
    location = / {
 
        if ($request_method = 'OPTIONS') {
 
            add_header 'Access-Control-Allow-Origin' '*';
 
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
 
            add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range';
 
            add_header 'Access-Control-Max-Age' 1728000;
 
            add_header 'Content-Type' 'text/plain; charset=UTF-8';
 
            add_header 'Content-Length' 0;
 
            return 204;
 
        }
        # Normal CORS headers for other requests
 
        add_header 'Access-Control-Allow-Origin' '*';
 
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
 
        add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range';
 
    }
    # Pass PHP scripts to PHP-FPM
 
    location ~ \.php$ {
 
        fastcgi_pass Asset_php:9000;
 
         include fastcgi_params;
 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
 
        fastcgi_param PATH_INFO $fastcgi_path_info;
 
        # Set appropriate headers
 
        fastcgi_param HTTP_PROXY "";  # Mitigate the HTTPoxy vulnerability
 
    }
    error_log /var/log/nginx/error.log;
 
    access_log /var/log/nginx/access.log;
 
}
